#############################################################################
# Makefile for building: fluidsim
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  fluidsim.pro
# Template: app
# Command: /home/vmiu/Qt5.7.1/5.7/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile fluidsim.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -std=c99 -std=c++11 -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/cuda/include -Iinc -I../../../Qt5.7.1/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /home/vmiu/Qt5.7.1/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = fluidsim1.0.0
DISTDIR = /home/vmiu/2020/cnn_fluids/fluidsim/.tmp/fluidsim1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/cuda/lib
LIBS          = $(SUBLIBS) -L/usr/local/cuda/lib64/ -L/usr/lib64/nvidia -lGL -lGLU -lX11 -lcudart -lGLEW -lcudnn -lcublas 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = bstrlib.c \
		Fluid3d.cpp \
		pez.c \
		pez.linux.c \
		Utility.cpp \
		toycnn.cpp 
OBJECTS       = Fluid3d_cuda.o \
		cnn_cuda.o \
		bstrlib.o \
		Fluid3d.o \
		pez.o \
		pez.linux.o \
		Utility.o \
		toycnn.o
DIST          = out_torch_order.bin \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/toolchain.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/lex.prf \
		fluidsim.pro bstrlib.h \
		gl3.h \
		pez.h \
		Utility.h \
		vmath.hpp \
		cnn.h \
		defines.h \
		toycnn.h bstrlib.c \
		Fluid3d.cpp \
		pez.c \
		pez.linux.c \
		Utility.cpp \
		toycnn.cpp
QMAKE_TARGET  = fluidsim
DESTDIR       = 
TARGET        = fluidsim


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fluidsim.pro ../../../Qt5.7.1/5.7/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/unix.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/linux.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/qconfig.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/toolchain.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/lex.prf \
		fluidsim.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile fluidsim.pro
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/unix.conf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/linux.conf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/sanitize.conf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/qconfig.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/toolchain.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/default_post.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/qml_debug.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/file_copies.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/yacc.prf:
../../../Qt5.7.1/5.7/gcc_64/mkspecs/features/lex.prf:
fluidsim.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile fluidsim.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Fluid3d.cu cnn.cu $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_cuda_d_make_all: Fluid3d_cuda.o cnn_cuda.o
compiler_cuda_d_clean:
	-$(DEL_FILE) Fluid3d_cuda.o cnn_cuda.o
Fluid3d_cuda.o: /usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/cuda_fp16.h \
		/usr/local/cuda/include/cuda_fp16.hpp \
		inc/helper_cuda.h \
		inc/helper_string.h \
		/usr/local/cuda/include/cudnn.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/crt/host_config.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/crt/device_functions.h \
		/usr/local/cuda/include/crt/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/crt/device_double_functions.h \
		/usr/local/cuda/include/crt/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/crt/sm_70_rt.h \
		/usr/local/cuda/include/crt/sm_70_rt.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/crt/common_functions.h \
		/usr/local/cuda/include/crt/math_functions.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/crt/math_functions.hpp \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		Fluid3d.cu
	CUDA_VISIBLE_DEVICES=1 /usr/local/cuda/bin/nvcc -D_DEBUG --use_fast_math -I"/usr/local/cuda/include" -I"inc" --machine 64 -arch=sm_35 -c -o Fluid3d_cuda.o Fluid3d.cu

cnn_cuda.o: /usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		inc/helper_cuda.h \
		inc/helper_string.h \
		defines.h \
		/usr/local/cuda/include/cudnn.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/crt/host_config.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/crt/device_functions.h \
		/usr/local/cuda/include/crt/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/crt/device_double_functions.h \
		/usr/local/cuda/include/crt/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/crt/sm_70_rt.h \
		/usr/local/cuda/include/crt/sm_70_rt.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/crt/common_functions.h \
		/usr/local/cuda/include/crt/math_functions.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/crt/math_functions.hpp \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		cnn.cu
	CUDA_VISIBLE_DEVICES=1 /usr/local/cuda/bin/nvcc -D_DEBUG --use_fast_math -I"/usr/local/cuda/include" -I"inc" --machine 64 -arch=sm_35 -c -o cnn_cuda.o cnn.cu

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_cuda_d_clean 

####### Compile

bstrlib.o: bstrlib.c bstrlib.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o bstrlib.o bstrlib.c

Fluid3d.o: Fluid3d.cpp Utility.h \
		vmath.hpp \
		pez.h \
		/usr/local/cuda/include/cuda_gl_interop.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/crt/host_config.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/crt/device_functions.h \
		/usr/local/cuda/include/crt/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/crt/device_double_functions.h \
		/usr/local/cuda/include/crt/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/crt/sm_70_rt.h \
		/usr/local/cuda/include/crt/sm_70_rt.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/crt/common_functions.h \
		/usr/local/cuda/include/crt/math_functions.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/crt/math_functions.hpp \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		inc/helper_cuda.h \
		inc/helper_string.h \
		inc/helper_cuda_gl.h \
		/usr/local/cuda/include/cuda_fp16.h \
		/usr/local/cuda/include/cuda_fp16.hpp \
		/usr/local/cuda/include/cudnn.h \
		cnn.cpp \
		cnn.h \
		defines.h \
		toycnn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Fluid3d.o Fluid3d.cpp

pez.o: pez.c pez.h \
		/usr/local/cuda/include/cuda_gl_interop.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		bstrlib.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pez.o pez.c

pez.linux.o: pez.linux.c pez.h \
		/usr/local/cuda/include/cuda_gl_interop.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		bstrlib.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o pez.linux.o pez.linux.c

Utility.o: Utility.cpp Utility.h \
		vmath.hpp \
		pez.h \
		/usr/local/cuda/include/cuda_gl_interop.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utility.o Utility.cpp

toycnn.o: toycnn.cpp toycnn.h \
		defines.h \
		/usr/local/cuda/include/cudnn.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/crt/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/crt/device_functions.h \
		/usr/local/cuda/include/crt/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/crt/device_double_functions.h \
		/usr/local/cuda/include/crt/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/crt/sm_70_rt.h \
		/usr/local/cuda/include/crt/sm_70_rt.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/crt/common_functions.h \
		/usr/local/cuda/include/crt/math_functions.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/crt/math_functions.hpp \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_launch_parameters.h \
		inc/helper_cuda.h \
		inc/helper_string.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toycnn.o toycnn.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

